!ArenaConfig
arenas:
  0: !Arena
    t: 0
    items:
    - !Item
      name: Wall
      positions:
        - !Vector3 {x: 33, y: 0, z: 20}
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
        - !Vector3 {x: -1, y: 5, z: -1}
      rotations: [0]

