!ArenaConfig
arenas:
  0: !Arena
    t: 1000
    items:

    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
        - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
        - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      colors:
        - !RGB {r: 153, g: 153, b: 153}
